In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("matches.csv")

In [5]:
data.head(10)

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
5,6,IPL-2017,Hyderabad,09-04-2017,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",A Deshmukh,NJ Llong,NaN
6,7,IPL-2017,Mumbai,09-04-2017,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,N Rana,Wankhede Stadium,Nitin Menon,CK Nandan,NaN
7,8,IPL-2017,Indore,10-04-2017,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,normal,0,Kings XI Punjab,0,8,AR Patel,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
8,9,IPL-2017,Pune,11-04-2017,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Delhi Daredevils,97,0,SV Samson,Maharashtra Cricket Association Stadium,AY Dandekar,S Ravi,NaN
9,10,IPL-2017,Mumbai,12-04-2017,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,JJ Bumrah,Wankhede Stadium,Nitin Menon,CK Nandan,NaN

In [6]:
data.tail(6)

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
750,11346,IPL-2019,Mohali,05-05-2019,Chennai Super Kings,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,KL Rahul,IS Bindra Stadium,KN Ananthapadmanabhan,C Shamshuddin,Bruce Oxenford
751,11347,IPL-2019,Mumbai,05-05-2019,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi
752,11412,IPL-2019,Chennai,07-05-2019,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould
753,11413,IPL-2019,Visakhapatnam,08-05-2019,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN
754,11414,IPL-2019,Visakhapatnam,10-05-2019,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
755,11415,IPL-2019,Hyderabad,12-05-2019,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               756 non-null    int64
 1   Season           756 non-null    object
 2   city             749 non-null    object
 3   date             756 non-null    object
 4   team1            756 non-null    object
 5   team2            756 non-null    object
 6   toss_winner      756 non-null    object
 7   toss_decision    756 non-null    object
 8   result           756 non-null    object
 9   dl_applied       756 non-null    int64
 10  winner           752 non-null    object
 11  win_by_runs      756 non-null    int64
 12  win_by_wickets   756 non-null    int64
 13  player_of_match  752 non-null    object
 14  venue            756 non-null    object
 15  umpire1          754 non-null    object
 16  umpire2          754 non-null    object
 17  umpire3          119 non-null    object
dtypes: int64(4), object(14)
memory usage: 106.4+ KB

In [9]:
data.shape

(756, 18)

In [17]:
data.isnull().sum()

id                   0
Season               0
city                 7
date                 0
team1                0
team2                0
toss_winner          0
toss_decision        0
result               0
dl_applied           0
winner               4
win_by_runs          0
win_by_wickets       0
player_of_match      4
venue                0
umpire1              2
umpire2              2
umpire3            637
dtype: int64

In [15]:
pd.isnull(data['city']).sum()

7

In [18]:
data.describe()

                 id  dl_applied  win_by_runs  win_by_wickets
count    756.000000  756.000000   756.000000      756.000000
mean    1792.178571    0.025132    13.283069        3.350529
std     3464.478148    0.156630    23.471144        3.387963
min        1.000000    0.000000     0.000000        0.000000
25%      189.750000    0.000000     0.000000        0.000000
50%      378.500000    0.000000     0.000000        4.000000
75%      567.250000    0.000000    19.000000        6.000000
max    11415.000000    1.000000   146.000000       10.000000

In [19]:
data.min()

C:\Users\admin\AppData\Local\Temp\ipykernel_2304\927168777.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  data.min()

id                                  1
Season                       IPL-2008
date                       01-04-2010
team1             Chennai Super Kings
team2             Chennai Super Kings
toss_winner       Chennai Super Kings
toss_decision                     bat
result                      no result
dl_applied                          0
win_by_runs                         0
win_by_wickets                      0
venue                ACA-VDCA Stadium
dtype: object

In [20]:
data.max()

C:\Users\admin\AppData\Local\Temp\ipykernel_2304\2904433368.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  data.max()

id                              11415
Season                       IPL-2019
date                       31-05-2008
team1             Sunrisers Hyderabad
team2             Sunrisers Hyderabad
toss_winner       Sunrisers Hyderabad
toss_decision                   field
result                            tie
dl_applied                          1
win_by_runs                       146
win_by_wickets                     10
venue                Wankhede Stadium
dtype: object

In [22]:
data.corr()

                      id  dl_applied  win_by_runs  win_by_wickets
id              1.000000   -0.011658    -0.039403       -0.012239
dl_applied     -0.011658    1.000000    -0.016349       -0.011631
win_by_runs    -0.039403   -0.016349     1.000000       -0.560420
win_by_wickets -0.012239   -0.011631    -0.560420        1.000000

In [23]:
data.value_counts()

id     Season    city       date        team1                        team2                  toss_winner            toss_decision  result  dl_applied  winner                 win_by_runs  win_by_wickets  player_of_match  venue                                      umpire1           umpire2          umpire3
7894   IPL-2018  Mumbai     07-04-2018  Mumbai Indians               Chennai Super Kings    Chennai Super Kings    field          normal  0           Chennai Super Kings    0            1               DJ Bravo         Wankhede Stadium                           Chris Gaffaney    A Nanda Kishore  Anil Chaudhary           1
11151  IPL-2019  Mumbai     03-04-2019  Mumbai Indians               Chennai Super Kings    Chennai Super Kings    field          normal  0           Mumbai Indians         37           0               HH Pandya        Wankhede Stadium                           Bruce Oxenford    Rod Tucker       Yeshwant Barde           1
11318  IPL-2019  Mumbai     13-04-2019  Mumbai Indians               Rajasthan Royals       Rajasthan Royals       field          normal  0           Rajasthan Royals       0            4               JC Buttler       Wankhede Stadium                           Nitin Menon       Nanda Kishore    Marais Erasmus           1
11317  IPL-2019  Kolkata    12-04-2019  Kolkata Knight Riders        Delhi Capitals         Delhi Capitals         field          normal  0           Delhi Capitals         0            7               S Dhawan         Eden Gardens                               Yeshwant Barde    O Nandan         Rod Tucker               1
11316  IPL-2019  Jaipur     11-04-2019  Rajasthan Royals             Chennai Super Kings    Chennai Super Kings    field          normal  0           Chennai Super Kings    0            4               MS Dhoni         Sawai Mansingh Stadium                     Bruce Oxenford    Ulhas Gandhe     Chris Gaffaney           1
                                                                                                                                                                                                                                                                                                                                 ..
7929   IPL-2018  Hyderabad  05-05-2018  Delhi Daredevils             Sunrisers Hyderabad    Delhi Daredevils       bat            normal  0           Sunrisers Hyderabad    0            7               Rashid Khan      Rajiv Gandhi International Stadium, Uppal  Bruce Oxenford    O Nandan         Virender Kumar Sharma    1
7928   IPL-2018  Pune       05-05-2018  Royal Challengers Bangalore  Chennai Super Kings    Chennai Super Kings    field          normal  0           Chennai Super Kings    0            6               RA Jadeja        Maharashtra Cricket Association Stadium    Nitin Menon       Yeshwant Barde   Marais Erasmus           1
7927   IPL-2018  Indore     04-05-2018  Kings XI Punjab              Mumbai Indians         Mumbai Indians         field          normal  0           Mumbai Indians         0            6               AS Yadav         Holkar Cricket Stadium                     S Ravi            Anil Dandekar    C Shamshuddin            1
7926   IPL-2018  Kolkata    03-05-2018  Chennai Super Kings          Kolkata Knight Riders  Kolkata Knight Riders  field          normal  0           Kolkata Knight Riders  0            6               SP Narine        Eden Gardens                               Kumar Dharmasena  A.D Deshmukh     Anil Chaudhary           1
11415  IPL-2019  Hyderabad  12-05-2019  Mumbai Indians               Chennai Super Kings    Mumbai Indians         bat            normal  0           Mumbai Indians         1            0               JJ Bumrah        Rajiv Gandhi Intl. Cricket Stadium         Nitin Menon       Ian Gould        Nigel Llong              1
Length: 118, dtype: int64

In [25]:
data.sort_values(by="date",ascending=True)

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
203,204,IPL-2010,Kolkata,01-04-2010,Kolkata Knight Riders,Deccan Chargers,Kolkata Knight Riders,bat,normal,0,Kolkata Knight Riders,24,0,SC Ganguly,Eden Gardens,K Hariharan,DJ Harper,NaN
708,11149,IPL-2019,Mohali,01-04-2019,Kings XI Punjab,Delhi Capitals,Delhi Capitals,field,normal,0,Kings XI Punjab,14,0,S Curran,IS Bindra Stadium,Anil Chaudhary,Chris Gaffaney,Vineet Kulkarni
77,78,IPL-2008,Jaipur,01-05-2008,Rajasthan Royals,Kolkata Knight Riders,Rajasthan Royals,bat,normal,0,Rajasthan Royals,45,0,SA Asnodkar,Sawai Mansingh Stadium,RE Koertzen,GA Pratapkumar,NaN
76,77,IPL-2008,Hyderabad,01-05-2008,Deccan Chargers,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,7,SE Marsh,"Rajiv Gandhi International Stadium, Uppal",BR Doctrove,RB Tiffin,NaN
138,139,IPL-2009,Durban,01-05-2009,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,8,0,Yuvraj Singh,Kingsmead,HDPK Dharmasena,S Ravi,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,203,IPL-2010,Delhi,31-03-2010,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils,bat,normal,0,Delhi Daredevils,67,0,KD Karthik,Feroz Shah Kotla,HDPK Dharmasena,SJA Taufel,NaN
201,202,IPL-2010,Chennai,31-03-2010,Royal Challengers Bangalore,Chennai Super Kings,Royal Challengers Bangalore,bat,normal,0,Chennai Super Kings,0,5,M Vijay,"MA Chidambaram Stadium, Chepauk",BG Jerling,RE Koertzen,NaN
707,11148,IPL-2019,Chennai,31-03-2019,Chennai Super Kings,Rajasthan Royals,Rajasthan Royals,field,normal,0,Chennai Super Kings,8,0,MS Dhoni,M. A. Chidambaram Stadium,O Nandan,Yeshwant Barde,Bruce Oxenford
706,11147,IPL-2019,Hyderabad,31-03-2019,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,118,0,J Bairstow,Rajiv Gandhi Intl. Cricket Stadium,S Ravi,KN Anantapadmanabhan,C Shamshuddin
115,116,IPL-2008,Mumbai,31-05-2008,Kings XI Punjab,Chennai Super Kings,Kings XI Punjab,bat,normal,0,Chennai Super Kings,0,9,M Ntini,Wankhede Stadium,Asad Rauf,DJ Harper,NaN

In [27]:
data.groupby('Season').mean()

                id  dl_applied  win_by_runs  win_by_wickets
Season
IPL-2008     88.50    0.034483    12.155172        3.810345
IPL-2009    146.00    0.052632    13.403509        3.157895
IPL-2010    204.50    0.000000    16.266667        3.166667
IPL-2011    271.00    0.041096    15.041096        3.630137
IPL-2012    344.50    0.000000    12.972973        3.256757
IPL-2013    419.50    0.000000    16.328947        2.986842
IPL-2014    487.50    0.016667    10.733333        3.750000
IPL-2015    547.00    0.033898    14.406780        2.508475
IPL-2016    606.50    0.066667    11.266667        4.066667
IPL-2017     30.00    0.016949    13.355932        3.457627
IPL-2018   7923.50    0.050000    11.250000        3.100000
IPL-2019  11281.85    0.000000    11.083333        3.366667